algo: MADDPG
seed: 123
gamma: 0.99
tau: 0.005
lr_actor: 0.001
lr_critic: 0.001
replay_size: 1000000
update_every: 10000
noise_sigma: 0.2
noise_sigma_final: 0.05
reward_weights:
  lambda_inv: 0.5
  kappa_imp: 0.2
  eta_cvar: 0.3
