# Enhanced Environment Configuration for Multi-Agent High-Frequency Trading
# =========================================================================

# Market Configuration
market_config:
  tick_size: 0.01
  decision_ms: 100
  max_spread_ticks: 10
  min_spread_ticks: 1
  volatility: 0.02
  mean_reversion_speed: 0.05
  liquidity_decay: 0.95
  impact_linear: 0.001
  impact_sqrt: 0.0005
  latency_ms: 1
  queue_position_noise: 0.1

# Risk Configuration
risk_config:
  max_inventory: 1000
  max_drawdown: 10000.0
  max_position_value: 50000.0
  kill_switch_drawdown: -5000.0
  max_order_rate_per_sec: 10.0
  max_pov: 0.05

# Reward Configuration
reward_config:
  lambda_inventory: 0.5
  lambda_impact: 0.2
  lambda_spread: 0.1
  lambda_risk: 1.0
  lambda_competition: 0.3
  profit_weight: 1.0
  inventory_penalty_power: 2.0

# Episode Configuration
episode_length: 1000
num_agents: 2
agent_types: ["market_maker", "market_taker"]

# Data Configuration
data_config:
  dataset_path: "data/features/dev_tensors.npz"
  scaler_path: "data/features/scaler.json"
  feature_dim: 8
  history_length: 20

# Simulation Configuration
simulation_config:
  num_episodes: 1000
  eval_episodes: 100
  random_seed: 42
  parallel_envs: 1
