# Feature Engineering Configuration
# ==================================

# Number of order book levels to use
K_levels: 10

# History window length
history_T: 20

# Time resolution
decision_ms: 100

# Rolling window parameters (ms) and MAs
windows:
  ofi_ms: 1000           # Order flow imbalance window
  realised_vol_ms: 2000  # Realized volatility window
  fast: 10               # Fast moving average
  slow: 30               # Slow moving average

# Auxiliary features to compute
aux:
  - spread               # Best ask - best bid
  - microprice           # Volume-weighted mid-price
  - imbalance            # Order book imbalance
  - mid_price
  - returns              # Price returns
  - volatility           # Rolling volatility
  - bid_value            # Bid price * quantity
  - ask_value            # Ask price * quantity
  - volatility_fast
  - volatility_slow
  - spread_ma_fast
  - spread_ma_slow
  - imbalance_ma_fast
  - imbalance_ma_slow
  - volume_ma_fast
  - volume_ma_slow

# Scaler configuration
scaler:
  type: robust           # 'robust' or 'standard'
  fit_on: dev            # Split to fit on (if applicable)

# Paths
paths:
  features: data/features
  interim: data/interim
  processed: data/processed
